language: python
python:
  - 3.7
  
addons:
  apt:
    packages:
      - maxima
     
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -r requirements.txt
  - pip install codecov
install:
  - pip install ".[test]" . < .travis_install.txt # install package + test dependencies
script: pytest # run tests
after_success:
  - codecov # submit coverage